# Generated by Django 5.2.6 on 2025-09-20 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title (max 200 characters)', max_length=200)),
                ('details', models.TextField(help_text='Detailed description of your project')),
                ('total_target', models.DecimalField(decimal_places=2, help_text='Target amount in EGP', max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('start_date', models.DateField(help_text='Campaign start date')),
                ('end_date', models.DateField(help_text='Campaign end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0.0, help_text='Current amount raised', max_digits=12)),
                ('image', models.ImageField(blank=True, help_text='Project image (optional)', null=True, upload_to='project_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from contributor')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-contributed_at'],
            },
        ),
    ]
